Force delete training jobs in integration test
aws/amazon-sagemaker-operator-for-k8s pull request #204
Opened 2022-11-21 23:05 UTC by ananth102

### What does this PR do / how does this improve the operators?

Sometimes training jobs do not get completely deleted, this is a workaround to get rid of them for now in the canary tests.

### Which issue(s) does this PR fix?

Fixes #

### Special notes for the reviewer:

### Does this PR require changes to documentation?

### All Submissions:

* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you written or refactored unit tests to cover the change?
* [ ] Have you ran all unit tests and ensured they are passing?
* [ n/a] Have you manually tested each feature that is being added/modified?
* [x ] Have you ensured you have not introduced linting errors?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-21 23:37 UTC, surajkota requested changes
Can you add how you tested these changes?

2022-11-21 23:37 UTC, surajkota commented on tests/codebuild/common.sh
> +      echo $job
print a more readable message

2022-11-21 23:37 UTC, surajkota commented on tests/codebuild/common.sh
> +  kubectl delete -n "$crd_namespace" hyperparametertuningjob --all
not needed

2022-11-22 02:29 UTC, ananth102 commented on tests/codebuild/common.sh
> +  kubectl delete -n "$crd_namespace" hyperparametertuningjob --all
replaced it with training job

2022-11-22 02:29 UTC, ananth102 commented on tests/codebuild/common.sh
> +      echo $job
done

2022-11-22 20:23 UTC, surajkota approved these changes
Thanks

2022-11-22 20:25 UTC, merged